version: "3"

tasks:
  run:
    desc: Run GPX to CSV
    dir: "src"
    cmds:
      - go run .

  build:
    desc: Build a binary targeting the current OS
    dir: "src"
    cmds:
      - |-
        CGO_ENABLED=0 \
          go build \
            -trimpath \
            -ldflags="-w -s -X 'chimbori.dev/gpx-to-csv/conf.BuildTimestamp=$(TZ=":America/Los_Angeles" date +"%Y-%m-%d %H:%M:%S")'"

  test:
    desc: Run all tests
    dir: "src"
    cmds:
      - go test -count=1 ./...

  testv:
    desc: Run all tests, with verbose output
    dir: "src"
    cmds:
      - go test -v -count=1 ./...

  fmt:
    desc: Reformat all source files, including templates
    dir: "src"
    cmds:
      - go mod tidy
      - gofumpt -l -w .
      - goimports -l -w .
      - golangci-lint fmt

  lint:
    desc: Lint sources
    dir: "src"
    cmds:
      - golangci-lint run

  update:
    desc: Update all dependencies
    dir: "src"
    deps: [fmt]
    cmds:
      - go get -u -t ./...
      - go clean -modcache
      - go mod tidy

  install:
    desc: Build and install the binary
    deps: [fmt]
    dir: "src"
    cmds:
      - go install .

  setup:
    desc: Setup pre-requisites on a new machine
    dir: "src"
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install mvdan.cc/gofumpt@latest
